### ISSUE TITLE
Create a FeatureOperations class that handles FeatureOperation instances

### ISSUE THREAD

**Issue by lorenz-gorini** [HK3-Lab-Team/pytrousse#4]
Methods in ``DataFrameWithInfo`` class like ``add_operation`` or ``find_operation_in_column`` are not fully related to ``DataFrameWithInfo`` class.
It could be useful to gather them inside a new FeatureOperations class that includes methods that handle FeatureOperation instances, able to add a new operation to the FeatureOperations instance, or finding an operation.
Therefore the ``feature_elaborations`` attribute of DataFrameWithInfo class could be an instance of the newly created FeatureOperations class.

**Comment by alessiamarcolini** [comment]
Given the new structure of `feature_operations` module, this is not relevant anymore
